### ISSUE TITLE
PaperSummaryTool出现异常bug

### ISSUE THREAD

**Issue by ruanrongman** [Undertone0809/promptulate#23]
在使用PaperSummaryTool的时候出现如下问题

```python
from promptulate.tools.paper.tools import PaperSummaryTool
from promptulate.utils.logger import get_logger, enable_log


def main():
    enable_log()
    tool = PaperSummaryTool()
    result = tool.run("Attention is all your need.")
    print(result)


if __name__ == "__main__":
    main()
```

```
[DEBUG] 2023-08-09 16:20:16 [broadcast-service] <get_paper_references> listen <PaperSummaryTool.run.get_paper_references> topic
[DEBUG] 2023-08-09 16:20:16 [broadcast-service] <get_translate> listen <PaperSummaryTool.run.get_translate> topic
[DEBUG] 2023-08-09 16:20:16 [broadcast-service] <get_opinion> listen <PaperSummaryTool.run.get_opinion> topic
[DEBUG] 2023-08-09 16:20:16 [broadcast-service] <get_keywords> listen <PaperSummaryTool.run.get_keywords> topic
[DEBUG] 2023-08-09 16:20:16 [broadcast-service] <get_advice> listen <PaperSummaryTool.run.get_advice> topic
[DEBUG] 2023-08-09 16:20:16 Starting new HTTPS connection (1): api.semanticscholar.org:443
[DEBUG] 2023-08-09 16:20:17 https://api.semanticscholar.org:443 "GET /graph/v1/paper/autocomplete?query=Attention%20is%20all%20your%20need.&limit=10 HTTP/1.1" 200 449
[DEBUG] 2023-08-09 16:20:17 Starting new HTTPS connection (1): api.semanticscholar.org:443
[DEBUG] 2023-08-09 16:20:19 https://api.semanticscholar.org:443 "POST /graph/v1/paper/batch?fields=title%2Curl%2Cabstract HTTP/1.1" 429 174
Traceback (most recent call last):
  File "D:\Programming\Python\Project\promptulate\private\paper_tool.py", line 19, in <module>
    main()
  File "D:\Programming\Python\Project\promptulate\private\paper_tool.py", line 14, in main
    result = tool.run("Attention is all your need.")
  File "D:\Programming\Python\Project\promptulate\promptulate\tools\base.py", line 50, in run
    result: Any = self._run(*args, **kwargs)
  File "D:\Programming\Python\Project\promptulate\promptulate\tools\paper\tools.py", line 132, in _run
    paper_info = self.semantic_scholar_query_tool.run(
  File "D:\Programming\Python\Project\promptulate\promptulate\tools\base.py", line 50, in run
    result: Any = self._run(*args, **kwargs)
  File "D:\Programming\Python\Project\promptulate\promptulate\tools\semantic_scholar\tools.py", line 26, in _run
    result = self.api_wrapper.get_paper(query, **kwargs)
  File "D:\Programming\Python\Project\promptulate\promptulate\tools\semantic_scholar\api_wrapper.py", line 95, in get_paper
    get_detail()
  File "D:\Programming\Python\Project\promptulate\promptulate\tools\semantic_scholar\api_wrapper.py", line 74, in get_detail
    if detail_item["paperId"] == original["id"]:
TypeError: string indices must be integers

Process finished with exit code 1

```

**Comment by Undertone0809** [comment]
semanticscholar接口的问题，其接口报错的时候和正常时候的返回值不一样，我在 #24 的部分修改了一些逻辑，把semanticscholar API的逻辑问题暴露出来了，如下所示，具体API访问量过高的问题不太好解决，或许我们可以尝试用其他的API？

```
promptulate.tips.NetWorkError: <SemanticScholarAPIWrapper.get_paper.get_detail> could not get data, reason: Too Many Requests. Please wait and try again or apply for a key for higher rate limits. https://www.semanticscholar.org/product/api#api-key-form
```

现在PaperSummaryTool是结合了semanticscholar API和arxiv API两者进行综合查询的，如果输入了arxiv id就用arxiv相关的工具查询论文标题，如果输入正常的论文标题就去semanticscholar API查询。

如果要避免出现上述的问题，可以加一个逻辑，在查询论文标题进行查询的时候semanticscholar API查询失败，我们就使用arxiv再搜一遍，如果都发生了报错或者没查到，那么就返回一个空数组。

现在的

**Comment by ruanrongman** [comment]
加个sleep限制速度，bug出现的概率大幅下降
`            if response.status_code != 200:
                raise NetWorkError("")

            detail_result = r.json()
            time.sleep(1)
           # print(detail_result)
            for original in self.current_result:
                for detail_item in detail_result:
                    if detail_item["paperId"] == original["id"]:
                        original.update(detail_item)
            return`

**Comment by ruanrongman** [comment]
sleep（0.1）就够了
